# Generated by Django 5.1.7 on 2025-07-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_project_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='horario_reunion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tema_investigacion',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('student_code', models.CharField(max_length=20)),
                ('institutional_mail', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='myapp.project')),
            ],
        ),
    ]
