# Generated by Django 5.1.7 on 2025-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_project_horario_reunion_project_tema_investigacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
