# Generated by Django 5.1.7 on 2025-07-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrantes',
            name='institutional_mail',
        ),
        migrations.RemoveField(
            model_name='integrantes',
            name='name',
        ),
        migrations.AddField(
            model_name='integrantes',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='student_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
