# Generated by Django 5.1.7 on 2025-07-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_integrantes_institutional_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='myapp.project'),
        ),
    ]
