# Generated by Django 5.1.7 on 2025-08-09 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_integrantes_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=150)),
                ('content_text', models.TextField(blank=True)),
                ('upload_path', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('date_uploaded', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='descripcion',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrantes', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.activity'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Metting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(null=True)),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('meeting_link', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stage'),
        ),
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='pendiente')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_completed', models.DateTimeField(null=True)),
                ('feedback', models.TextField(blank=True)),
                ('important', models.BooleanField(default=False)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.document')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
    ]
