# Generated by Django 5.1.7 on 2025-08-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_activity_document_stage_remove_task_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskproject',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='taskproject',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='taskproject',
            old_name='task_id',
            new_name='task',
        ),
    ]
