# Generated by Django 5.1.7 on 2025-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_document_id_taskproject_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(),
        ),
    ]
