# Generated by Django 5.1.7 on 2025-08-13 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_activity_description_alter_stage_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content_text',
            new_name='content_doc',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_title',
            new_name='title_doc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.document'),
        ),
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='pendiente'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_path',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='metting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TaskProject',
        ),
    ]
