# Generated by Django 5.1.7 on 2025-08-13 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_content_text_document_content_doc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Studentuser',
        ),
    ]
