# Generated by Django 5.1.7 on 2025-09-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_task_date_completed_alter_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_start', models.DateTimeField()),
                ('meeting_end', models.DateTimeField()),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('meeting_link', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Metting',
        ),
    ]
