# Generated by Django 5.1.7 on 2025-09-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_meeting_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='title',
        ),
    ]
